package dbscan
import dbscan.LabeledPoint._
import org.apache.spark.internal.Logging
import org.apache.spark.mllib.linalg.Vector
import org.apache.spark.rdd.RDD

import scala.collection.parallel.mutable.ParArray

object DBSCAN {

  /**
   * DBSCAN Clustering Model object
   *
   * @param data training points stored as RDD[Vector]
   * @param eps the maximum distance between two points to be considered as part of the same cluster
   * @param minPoints the minimum number of points required to form a cluster
   * @param maxPointsPerPartition the largest number of points in a single partition
   */

  // return an instance of DBSCAN trained class
  def train(
             data: RDD[ParArray[Double]],
             eps: Double,
             minPoints: Int,
             maxPointsPerPartition: Int): DBSCAN = {

    new DBSCAN(eps, minPoints, maxPointsPerPartition, null, null).train(data)

  }

}
  /**
   * DBSCAN Clustering Model class
   *
   * @param eps the maximum distance between two points to be considered as part of the same cluster
   * @param minPoints the minimum number of points required to form a cluster
   * @param maxPointsPerPartition the largest number of points in a single partition
   * @param partitions boxes generated by custom partitioner to create balanced sections
   * @param labeledPartitionedPoints RDD[LabeledPoint]: a LabeledPoint is an object which contains point coordinates and other relevant informations
   */
class DBSCAN private (
                       val eps: Double,
                       val minPoints: Int,
                       val maxPointsPerPartition: Int,
                       @transient val partitions: List[(Int, Rectangle)],
                       @transient private val labeledPartitionedPoints: RDD[(Int, LabeledPoint)])

  extends Serializable with Logging {

  type Margins = (Rectangle, Rectangle, Rectangle)
  type ClusterId = (Int, Int)

  def minimumRectangleSize: Double = 2 * eps

  def labeledPoints: RDD[LabeledPoint] = {
    labeledPartitionedPoints.values
  }

  def train(data: RDD[ParArray[Double]]): DBSCAN = {

    // generate the smallest rectangles that split the space and count how many points are contained in each one of them
    val minimumRectanglesWithCount =
    data
      .map(toMinimumBoundingRectangle)
      .map((_, 1))
      .aggregateByKey(0)(_ + _, _ + _)
      .collect()
      .toSet

    val localPartitions = Partitioner
      .partition(minimumRectanglesWithCount, maxPointsPerPartition, minimumRectangleSize)

    val localMargins =
      localPartitions
        .map({ case (p, _) => (p.shrink(eps), p, p.shrink(-eps)) })
        .zipWithIndex

    val partitionsNum = localPartitions.size

    val margins = data.context.broadcast(localMargins)

    // assign each point to its proper partition
    val duplicated = for {
      point <- data.map(Point)
      ((inner, main, outer), id) <- margins.value
      if outer.contains(point)
    } yield (id, point)

    // perform local dbscan
    val clustered =
      duplicated
        .groupByKey(partitionsNum)
        .flatMapValues(points =>
          new DBSCANCore(eps, minPoints).fit(points))
        .cache()

    // find all candidate points for merging clusters and group them
    val mergePoints =
      clustered
        .flatMap({
          case (partition, point) =>
            margins.value
              .filter({
                case ((inner, main, _), _) => main.contains(point) && !inner.almostContains(point)
              })
              .map({
                case (_, newPartition) => (newPartition, (partition, point))
              })
        })
        .groupByKey()

    // find all clusters with aliases from merging candidates
    val adjacencies =
      mergePoints
        .flatMapValues(findAdjacencies)
        .values
        .collect()

    // generated adjacency graph
    val adjacencyGraph = adjacencies.foldLeft(Graph[ClusterId]()) {
      case (graph, (from, to)) => graph.connect(from, to)
    }

    // find all cluster ids
    val localClusterIds =
      clustered
        .filter({ case (_, point) => point.flag != Flag.Noise })
        .mapValues(_.cluster)
        .distinct()
        .collect()
        .toList

    // assign a global Id to all clusters, where connected clusters get the same id
    val (total, clusterIdToGlobalId) = localClusterIds.foldLeft((0, Map[ClusterId, Int]())) {
      case ((id, map), clusterId) => {

        map.get(clusterId) match {
          case None => {
            val nextId = id + 1
            val connectedClusters = adjacencyGraph.getConnected(clusterId) + clusterId
            val toadd = connectedClusters.map((_, nextId)).toMap
            (nextId, map ++ toadd)
          }
          case Some(x) =>
            (id, map)
        }

      }
    }

    val clusterIds = data.context.broadcast(clusterIdToGlobalId)

    // relabel non-duplicated points
    val labeledInner =
      clustered
        .filter(isInnerPoint(_, margins.value))
        .map {
          case (partition, point) => {

            if (point.flag != Flag.Noise) {
              point.cluster = clusterIds.value((partition, point.cluster))
            }

            (partition, point)
          }
        }

    // de-duplicate and label merge points
    val labeledOuter =
      mergePoints.flatMapValues(partition => {
        partition.foldLeft(Map[Point, LabeledPoint]())({
          case (all, (partition, point)) =>

            if (point.flag != Flag.Noise) {
              point.cluster = clusterIds.value((partition, point.cluster))
            }

            all.get(point) match {
              case None => all + (point -> point)
              case Some(prev) => {
                // override previous entry unless new entry is noise
                if (point.flag != Flag.Noise) {
                  prev.flag = point.flag
                  prev.cluster = point.cluster
                }
                all
              }
            }
        }).values
      })
    // getting final clusters with their own points
    val finalPartitions = localMargins.map {
      case ((_, p, _), index) => (index, p)
    }

    // return DBSCAN trained model
    new DBSCAN(eps,minPoints,maxPointsPerPartition,finalPartitions,labeledInner.union(labeledOuter))
  }

  // check if is a non duplicate point
  private def isInnerPoint(
                            entry: (Int, LabeledPoint),
                            margins: List[(Margins, Int)]): Boolean = {
    entry match {
      case (partition, point) =>
        val ((inner, _, _), _) = margins.filter({
          case (_, id) => id == partition
        }).head

        inner.almostContains(point)
    }
  }

  //search for adjacent points in the built adjacencies graph
  private def findAdjacencies(
                               partition: Iterable[(Int, LabeledPoint)]): Set[((Int, Int), (Int, Int))] = {

    val zero = (Map[Point, ClusterId](), Set[(ClusterId, ClusterId)]())

    val (seen, adjacencies) = partition.foldLeft(zero)({

      case ((seen, adjacencies), (partition, point)) =>

        // noise points are not relevant for adjacencies
        if (point.flag == Flag.Noise) {
          (seen, adjacencies)
        } else {

          val clusterId = (partition, point.cluster)

          seen.get(point) match {
            case None                => (seen + (point -> clusterId), adjacencies)
            case Some(prevClusterId) => (seen, adjacencies + ((prevClusterId, clusterId)))
          }

        }
    })

    adjacencies
  }

  // evaluate partition rectangle
  private def toMinimumBoundingRectangle(vector: ParArray[Double]): Rectangle = {
    val point = Point(vector)
    val x = corner(point.x)
    val y = corner(point.y)
    Rectangle(x, y, x + minimumRectangleSize, y + minimumRectangleSize)
  }

  // evaluate corner point of partitions
  private def corner(p: Double): Double =
    (shiftIfNegative(p) / minimumRectangleSize).intValue * minimumRectangleSize

  private def shiftIfNegative(p: Double): Double =
    if (p < 0) p - minimumRectangleSize else p

}
